### ISSUE TITLE
[Scoreboard] Forced colors when no colors are used

### ISSUE THREAD

**Issue by WMGameLive** [NEZNAMY/TAB#1189]
### Server version

1.20.2

### TAB version

4.1.2

### Describe the bug

Colored output preview in parse command not match real output, see screenshots below.

### Steps to reproduce

Type some texts like "Text&&rcText" on tab, you will see.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
I didn't understand your explanation. Sounds like conditions may help with this though.

**Comment by WMGameLive** [comment]
> I didn't understand your explanation. Sounds like conditions may help with this though.

Sorry for my bad english.

My nickname plugin have a placeholder like this:
![image](https://github.com/NEZNAMY/TAB/assets/25265603/3631815c-17e8-484c-8945-94c87696dc72)

If the player does not have permission, it will keep the color code like this:
![image](https://github.com/NEZNAMY/TAB/assets/25265603/80a9de14-acc5-4fbc-9d94-94669d2ec6c5)

But if I put this placeholder on Tab, it will still show the color:
![image](https://github.com/NEZNAMY/TAB/assets/25265603/9b29b2ea-1e3d-4020-85a5-5c5aa721d45b)

So I need a way to display only the original text of the placeholder.

**Comment by NEZNAMY** [comment]
Sounds like you want some changes to nickname placeholder code. TAB cannot change code of other plugins. Request this change in your nickname plugin.

**Comment by WMGameLive** [comment]
so it is no way to just show the text like the 'Raw colors:' in last screenshot? I am not want to change that placeholder code, keep color codes when player don't have permission is what I want.

**Comment by NEZNAMY** [comment]
Maybe somehow with conditions you could build it up, but plugin doesn't offer this directly. What you are asking for is way too specific to your case to be added into the plugin.

**Comment by WMGameLive** [comment]
This is just an example, not the only case, if some placeholders contain a '&', it will get replaced too, if I just want to display a & or # with some number, what can I do?
![image](https://github.com/NEZNAMY/TAB/assets/25265603/2f86e29a-2d53-48a9-a8c6-2f7cfcf27bbd)

**Comment by NEZNAMY** [comment]
You can use a workaround, for example `A&&rB`.

**Comment by WMGameLive** [comment]
> You can use a workaround, for example `A&&rB`.

ok, that work for keep the code but still get colored.
![image](https://github.com/NEZNAMY/TAB/assets/25265603/aeb439cd-cc6b-4206-818f-a6f098037b67)
![image](https://github.com/NEZNAMY/TAB/assets/25265603/20ea56b0-a957-438a-b872-323026599b20)

> lines:
      - "&7◆&m                           &7◆"
      - "  #ddffff&l%player%"
      - "   &f◆ Nick: &r%nickname_name%"

**Comment by NEZNAMY** [comment]
Not parsing colors for players without permission is not an available feature.

**Comment by WMGameLive** [comment]
But you "Colored output" not even match the real output.

**Comment by WMGameLive** [comment]
> But you "Colored output" not even match the real output.
> 
> Just type some text like "Text&&rcText" will also return a strange output, why dose it become "Text&&ccText" ![image](https://private-user-images.githubusercontent.com/25265603/293421067-83130d04-1043-4abb-a1f4-4601f9a7a7d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5NjU5NDgsIm5iZiI6MTcwMzk2NTY0OCwicGF0aCI6Ii8yNTI2NTYwMy8yOTM0MjEwNjctODMxMzBkMDQtMTA0My00YWJiLWExZjQtNDYwMWY5YTdhN2Q2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMwVDE5NDcyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhNDQ4NzIzZjhkMzY3NmU5YTYwNmM1OWZlNmE4ODBhNDk3YjE0MDRiN2ExNzg5OTY5MTlkM2I1M2M0NzdjNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3KjcwwiiHm2QKv3aonNSeBCsQRpuNBqdrI1MTfiFkC0)

Will you fix this?

**Comment by NEZNAMY** [comment]
Yes, bugs are being fixed. You just need to accept the fact that I am not dedicating my existence to a free plugin.

**Comment by WMGameLive** [comment]
I understand. You only give me an emoji and I don't understand what it mean so I just wanted to confirm if you plan to fix this bug. Thanks, and sorry to bother you.

**Comment by NEZNAMY** [comment]
Yes, bug fixing is a [provided service](https://github.com/NEZNAMY/TAB?tab=readme-ov-file#provided-services).

**Comment by NEZNAMY** [comment]
I have fixed the red color issue in scoreboard. Other than that, I'm not sure what the issue is. Using the `&` symbol followed by a color code, but not wanting it to be treated as color code is something people usually don't do. Your case is very specific and must have a decent workaround available. I don't even think other plugins offer this.

**Comment by NEZNAMY** [comment]
It always amazes me how people expect me to fix everything immediately but once I fix it, they have no interest in actually testing the fix.

**Comment by WMGameLive** [comment]
> It always amazes me how people expect me to fix everything immediately but once I fix it, they have no interest in actually testing the fix.

Sorry, I didn't receive notification of your last reply.

I've compiled and tested it now, the issue still exist.
![image](https://github.com/NEZNAMY/TAB/assets/25265603/ee2349ce-2b51-4acc-a45f-ff4748503e0e)
![image](https://github.com/NEZNAMY/TAB/assets/25265603/1ca3179c-3c0c-4506-a5f8-a0b09db50a81)

**Comment by NEZNAMY** [comment]
```
    scoreboard:
      title: "&6&lTEST"
      lines:
      - '&fTest&&ra123'
      - '&fTest&&rb456'
      - '&fTest&&rc789'
```

![image](https://github.com/NEZNAMY/TAB/assets/6338394/02a503e9-9c63-489f-9b69-2f68aad416af)

Are you sure you have the latest code?

**Comment by WMGameLive** [comment]
> ```
>     scoreboard:
>       title: "&6&lTEST"
>       lines:
>       - '&fTest&&ra123'
>       - '&fTest&&rb456'
>       - '&fTest&&rc789'
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/6338394/294623624-02a503e9-9c63-489f-9b69-2f68aad416af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0OTQxNjksIm5iZiI6MTcwNDQ5Mzg2OSwicGF0aCI6Ii82MzM4Mzk0LzI5NDYyMzYyNC0wMmE1MDNlOS05YzYzLTQ4OWYtOWI2OS0yZjY4YWFkNDE2YWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDVUMjIzMTA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDFlN2EwNDgzYTdhZmI3MThkMjEzMjYyMjkyMDhhOWExZDhjNDEzNTEyNzAxYWFmOTVkZmQxZTUxYWM3ZDdkNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1XBf_y-oLq73neZaU0uD0waPdW7OUgoJEacRljTrk5I)
> 
> Are you sure you have the latest code?

I just downloaded it, so it should be the latest I guess.

**Comment by NEZNAMY** [comment]
You can download it from github actions and you don't need to compile anything.

**Comment by WMGameLive** [comment]
> You can download it from github actions and you don't need to compile anything.

Oh that works. Thank you so much!
![image](https://github.com/NEZNAMY/TAB/assets/25265603/abdf9a18-516f-4c15-90f5-908181502dd8)

**Comment by NEZNAMY** [comment]
Anything else?

**Comment by WMGameLive** [comment]
no
