### ISSUE TITLE
BEDROCK PLAYER BUNGEECORD SERVER 'di-health' EROR SPAM

### ISSUE THREAD

**Issue by MuratAb54** [NEZNAMY/TAB#1204]
### Server version

1.20.2

### TAB version

4.1.2

### Stack trace

[11:23:05 INFO] [Geyser-BungeeCord]: Tried to update score without the existence of its requested objective 'di-health'

### Additional info

When bedrock players take damage or regenerate, an error like this constantly occurs on my Bungecord server.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
This objective does not come from TAB, see [Scoreboard objective and team naming](https://github.com/NEZNAMY/TAB/wiki/Additional-information#scoreboard-objective-and-team-naming).

**Comment by MuratAb54** [comment]
But when I delete the tab plugin, the error goes away.

**Comment by NEZNAMY** [comment]
Can be a coincidence or you just weren't able to reproduce it so quickly. The plugin is not preventing other plugins from registering objectives and this objective name does not come from TAB.

**Comment by MuratAb54** [comment]
So where could this error be coming from?

**Comment by NEZNAMY** [comment]
Another plugin registering objective called "di-health". You need to find out which one it is.

**Comment by MuratAb54** [comment]
Is there an easy way to find it?

**Comment by NEZNAMY** [comment]
No, assuming none of your plugins have "DI" initials, the only way is to remove it using /scoreboard command and then removing plugins one by one until it stops. This is however out of scope of this issue tracker.

**Comment by MuratAb54** [comment]
As a result, this problem occurs when the tab add-on conflicts with a different add-on and the player gets damaged or health is renewed. I tried deleting all the add-ons one by one and lastly, I deleted the tab add-on and it did not give any error.

**Comment by NEZNAMY** [comment]
The objective could be registered on the server scoreboard. Are you sure you removed it every time?

**Comment by MuratAb54** [comment]
Yes, it always gives an error, it never stops, if there is no bedrock player on the server, it does not give any error, but if there is a bedrock player on the server and they take damage, it gives an error. There is a health indicator on the players, I tried turning it off and nothing changed.

**Comment by MuratAb54** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/125699753/35e73440-3c2f-46cd-aa5c-450a3775e44e)

**Comment by NEZNAMY** [comment]
Check `/scoreboard objectives list`. Are you sure it's there even after removing it with only TAB installed?

**Comment by MuratAb54** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/125699753/84e5cfd0-c16c-4297-8342-65fe4162fb0b)



Yes, I'm sure it only gives an error when the tab is loaded.

**Comment by NEZNAMY** [comment]
Did you delete that objective before every restart and plugin removal?

**Comment by MuratAb54** [comment]
I'm deleting that target now, I'll try again and let you know.

**Comment by NEZNAMY** [comment]
Why only now? I asked you 2 times before to do it.

**Comment by MuratAb54** [comment]
Even though I deleted it, the same error is repeated again.

**Comment by NEZNAMY** [comment]
Then you have a plugin adding it back. Are you sure you deleted all plugin besides TAB? Or, only deleted TAB?

**Comment by NEZNAMY** [comment]
Directory? You were supposed to delete the jar. Or just let's go the easy way - remove the objective, remove TAB jar and restart. If it reappears, will you understand it's not TAB doing it?

**Comment by MuratAb54** [comment]
I had done that operation before and it gave an error again.

**Comment by NEZNAMY** [comment]
So you have it without TAB installed? That's amazing, isn't it?

**Comment by MuratAb54** [comment]
No, while the tab plugin was installed, I deleted all other plugins, the error was still occurring, I last deleted the tab plugin, and the error was resolved after that.

**Comment by NEZNAMY** [comment]
Are you using TAB's belowname feature? If yes, disable it. It can totally explain the issue. Alternatively, remove TAB and see if the objective is registered using the command.

**Comment by MuratAb54** [comment]
I tried with belowname turned off and the error persisted.

**Comment by NEZNAMY** [comment]
Did you restart the server after disabling it? Did you try the second option?

**Comment by MuratAb54** [comment]
yes I tried everything. I'm opening a different test server right now. I'll just install the tab plugin and try it that way.

**Comment by NEZNAMY** [comment]
Based on the provided information it looks like another plugin besides TAB tried to send belowname, but TAB ended up being the one who has overridden the other one. Can you send your config? Did you have belowname enabled? Is it disabled now? Do you still have no idea which other plugins is registering the objective?

**Comment by MuratAb54** [comment]
Ok, I solved the error, now I deleted the tab plugin like this and added it again, it doesn't give an error without adding the scoreborad and tablist part that I set, it doesn't give an error when I add them, but if I set the belowname-objective setting to true, it starts giving an error. Even if I open and close it once, the error does not stop, so the error does not stop in the belowname-objective part.

**Comment by NEZNAMY** [comment]
So my theory was correct. How am I supposed to resolve this compatibility issue with plugins trying to do the same thing?

**Comment by NEZNAMY** [comment]
Makes perfect sense to me. How do you want me to resolve it? I already made belowname disabled by default. Should I completely remove the feature for everyone so they cannot accidentally enable it when using a plugin "di"?

**Comment by MuratAb54** [comment]
The feature is very nice, it should not be removed, there may be a different method.

**Comment by NEZNAMY** [comment]
What do you want me to do then?

**Comment by MuratAb54** [comment]
I'm not exactly sure, I solved the error and set the belowname setting to false, it doesn't give an error anymore, but others should not get the same error. I think I know which plugin is causing the error, but I'm not sure, I'm sending the image of the plugin.


![image](https://github.com/NEZNAMY/TAB/assets/125699753/17bcc4ed-c2fd-44b4-87c5-af27800f4b82)

**Comment by MuratAb54** [comment]
If you want to talk to the producer of this plugin, is there a line like di healt or a setting that shows the health indicator, maybe you can solve it.

**Comment by NEZNAMY** [comment]
I don't see the point of talking to the author. You configured 2 plugins to do the same and that won't work. I don't know how am I supposed to resolve this.

**Comment by NEZNAMY** [comment]
So you opened an issue requesting code change and don't know what do you want me to do?

**Comment by MuratAb54** [comment]
No, no, I came to ask how to solve the error, I solved the error, I don't have a problem now, the error is solved.

**Comment by NEZNAMY** [comment]
It's not solved, you did not ask for help, you opened a bug report and it wasn't fixed.

**Comment by MuratAb54** [comment]
sorry I didn't notice
