### ISSUE TITLE
"disable-features-in-worlds:" only works for the first world

### ISSUE THREAD

**Issue by Jadiction** [NEZNAMY/TAB#94]
**Server version**
This server is running Paper version git-Paper-47 (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)

**Plugin version** ("latest" is not a version)
TAB version 2.6.2

**Describe the bug**
In the config where you can disable features in specific worlds, it only seems to work on the first world. For example, I have:
```
disable-features-in-worlds:
  header-footer:
  - disabledworld
  tablist-names:
  - disabledworld
  nametag:
  - disabledworld
  tablist-objective:
  - disabledworld
  bossbar:
  - disabledworld
  belowname:
  - world1
  - world2
  - world3
```
In the example above, only world1 will disable the "belowname" feature. "world2" and "world3" will still have it enabled. 

**How to reproduce**
Add multiple worlds to a disabled feature.

**Comment by rodrigozamorad** [comment]
Try the last version from discord. An issue with disabled world's was fixed in one development build.

**Comment by Jadiction** [comment]
@rodrigozamorad Thanks, but I tried using the pre-released version and even the newest version that came out today (v2.6.3) and it still is not fixed.

**Comment by NEZNAMY** [comment]
Can you try to swap world names in config if it applies only to the first one again ?

**Comment by Jadiction** [comment]
Hm, for some reason it's only working for one specific world, not the first listed world. Not sure if it helps but my config is:
```  - creative
  - spawn
  - spleef
  - anarchy
  - anarchy_nether
  - anarchy_the_end```
Only 'spawn' world will allow the below tag to be disabled.

**Comment by NEZNAMY** [comment]
Does it not work for other features when disabling them in worlds either or this one only ?

**Comment by Jadiction** [comment]
I've only tried with "belowname". For some reason, it only disabled it for my spawn world, not the others.

**Comment by NEZNAMY** [comment]
Can you test other features too ?

**Comment by Jadiction** [comment]
Tested them and they work and after looking at the configuration file more, I may have mistaken the "belowname" feature for the "belowname" property that you can add in groups. For example, my "`_OTHER_`" group was "string 1", and I wanted it only show on certain worlds. I see at the bottom there's a "belowname vanilla feature" which is more likely what it's referring to. 

The reason my spawn world "disabled" belowname was because awhile back I found a "workaround" (or so I thought it was a workaround) which was setting belowname to an empty string for `per-world-settings`.
```
  spawn:
    Groups:
      _OTHER_:
        belowname: ''
```

**Comment by NEZNAMY** [comment]
So is this resolved now ?

**Comment by Jadiction** [comment]
Yeah, assuming my new findings are correct all is fine.

On a side note, the tablist-objective doesn't seem to change the yellow number in the tab list. 
Even while set to "NONE" it shows this 
![](https://image.prntscr.com/image/qNbsUAWHSMOrvGI2gkOfVA.png)

**Comment by NEZNAMY** [comment]
Are you sure it's tab doing it and you only have the line once in your config ?

**Comment by Jadiction** [comment]
None of my plugins modify the tab list or nametags, since I have tab to do it. The only lines in my config relating to tablist objective are 
```
tablist-objective: NONE
tablist-objective-custom-value: ''
```

**Comment by NEZNAMY** [comment]
Try uninstalling tab if it still appears.

**Comment by Jadiction** [comment]
Yeah, it's still there when I don't use tab.

**Comment by NEZNAMY** [comment]
Caused by another plugin. Try deleting world/data/scoreboard.dat

**Comment by Jadiction** [comment]
It's not another plugin. This is default vanilla behavior, I can have no plugins and that number would be there.
